#!/usr/bin/env bash
# Build the VayOBD .deb (spec 006 / FR-014 / SC-007).
#
# Single entry point. From a clean checkout:
#   ./packaging/build.sh                            # version = `git describe`
#   ./packaging/build.sh --version 1.2.3            # explicit
#
# Outputs:  dist/vayobd_<version>_amd64.deb
#
# Prereqs:  cargo, npm, uv, nfpm. See scripts/setup-linux.sh comment for nfpm.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PKG_DIR="${REPO_ROOT}/packaging"
BUILD_DIR="${PKG_DIR}/build"
STAGE_DIR="${BUILD_DIR}/dist"
OUT_DIR="${REPO_ROOT}/dist"

VAYOBD_VERSION="${VAYOBD_VERSION:-}"
VAYOBD_COMMIT="${VAYOBD_COMMIT:-}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --version)
            VAYOBD_VERSION="$2"; shift 2 ;;
        --commit)
            VAYOBD_COMMIT="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,8p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *)
            echo "Unknown argument: $1" >&2; exit 2 ;;
    esac
done

if [[ -z "${VAYOBD_VERSION}" ]]; then
    if command -v git >/dev/null 2>&1 && git -C "${REPO_ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        VAYOBD_VERSION="$(git -C "${REPO_ROOT}" describe --always --dirty --tags 2>/dev/null \
            || git -C "${REPO_ROOT}" describe --always --dirty 2>/dev/null \
            || echo "0.0.0-snapshot")"
    else
        VAYOBD_VERSION="0.0.0-snapshot"
    fi
fi

# Strip any leading "v" from a tag-derived version so dpkg accepts it.
VAYOBD_VERSION="${VAYOBD_VERSION#v}"

if [[ -z "${VAYOBD_COMMIT}" ]]; then
    if command -v git >/dev/null 2>&1 && git -C "${REPO_ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        VAYOBD_COMMIT="$(git -C "${REPO_ROOT}" rev-parse HEAD 2>/dev/null || echo unknown)"
    else
        VAYOBD_COMMIT="unknown"
    fi
fi

echo "==> Building VayOBD .deb (version ${VAYOBD_VERSION}, commit ${VAYOBD_COMMIT})"

# Required tools — fail fast with actionable messages.
for tool in cargo npm uv nfpm; do
    if ! command -v "${tool}" >/dev/null 2>&1; then
        case "${tool}" in
            nfpm) echo "ERROR: nfpm is missing. Install it once: see scripts/setup-linux.sh §nfpm." >&2 ;;
            *)    echo "ERROR: ${tool} is required to build the .deb. Run scripts/setup-linux.sh first." >&2 ;;
        esac
        exit 1
    fi
done

# ─── 0. Fresh stage ──────────────────────────────────────────────────────────
rm -rf "${BUILD_DIR}"
mkdir -p "${STAGE_DIR}/usr/lib/vayobd/bin" "${STAGE_DIR}/usr/lib/vayobd/venv" "${STAGE_DIR}/usr/share/vayobd"
mkdir -p "${OUT_DIR}"

# ─── 1. Engine binary ────────────────────────────────────────────────────────
echo "==> Building ree-debug-cli (cargo build --release)"
(
    cd "${REPO_ROOT}/engine"
    cargo build --release --bin ree-debug-cli
)
cp "${REPO_ROOT}/engine/target/release/ree-debug-cli" "${STAGE_DIR}/usr/lib/vayobd/bin/ree-debug-cli"

# ─── 2. Frontend SPA ─────────────────────────────────────────────────────────
echo "==> Building frontend SPA (npm ci && npm run build)"
(
    cd "${REPO_ROOT}/frontend"
    npm ci --silent
    npm run build --silent
)
cp -a "${REPO_ROOT}/frontend/dist/." "${STAGE_DIR}/usr/share/vayobd/spa/"

# ─── 3. Embed version + commit (FR-013) ──────────────────────────────────────
echo "==> Writing backend/_version.py"
cat > "${REPO_ROOT}/backend/src/vayobd/_version.py" <<EOF
# Auto-generated by packaging/build.sh — do not commit, do not hand-edit.
__version__ = "${VAYOBD_VERSION}"
__commit__ = "${VAYOBD_COMMIT}"
EOF

# ─── 4. Bundled Python interpreter (python-build-standalone) ─────────────────
# The .deb ships a self-contained CPython under /usr/lib/vayobd/python/
# so it works on any glibc-based amd64 Linux (Ubuntu 24.04, 25.10, Debian,
# …) regardless of the target machine's system Python. uv pulls the
# fully-relocatable tarball from astral-sh/python-build-standalone and
# caches it under ~/.local/share/uv/python/.
TARGET_PY_VERSION="${VAYOBD_TARGET_PYTHON_VERSION:-3.12}"
PY_STAGE_DIR="${STAGE_DIR}/usr/lib/vayobd/python"

echo "==> Provisioning bundled Python (${TARGET_PY_VERSION}, python-build-standalone via uv)"
uv python install "${TARGET_PY_VERSION}" >/dev/null
UV_PY_BIN="$(uv python find "${TARGET_PY_VERSION}" --managed-python 2>/dev/null || uv python find "${TARGET_PY_VERSION}")"
if [[ -z "${UV_PY_BIN}" || ! -x "${UV_PY_BIN}" ]]; then
    echo "ERROR: could not resolve a uv-managed Python ${TARGET_PY_VERSION}." >&2
    echo "       Run: uv python install ${TARGET_PY_VERSION}" >&2
    exit 1
fi
# Strip /bin/python3.X to get the install root (e.g. .../cpython-3.12-…-gnu).
UV_PY_ROOT="$(dirname "$(dirname "${UV_PY_BIN}")")"
echo "    bundled python: ${UV_PY_ROOT}"

# Copy the interpreter into the stage tree, preserving the internal
# symlinks (python -> python3 -> python3.12 etc.) so the binary isn't
# duplicated three times. python-build-standalone tarballs are
# self-contained — no symlinks point outside the tree — so a plain
# `cp -a` is safe and saves ~60 MB on the final .deb.
mkdir -p "${PY_STAGE_DIR}"
cp -a "${UV_PY_ROOT}/." "${PY_STAGE_DIR}/"

# Slim the bundle: drop dev headers, man pages, tests, REPL niceties, and
# convenience binaries that vayobd doesn't need. Saves ~25-30 MB.
rm -rf "${PY_STAGE_DIR}/include"
rm -rf "${PY_STAGE_DIR}/share"
rm -rf "${PY_STAGE_DIR}"/lib/python*/test
rm -rf "${PY_STAGE_DIR}"/lib/python*/idlelib
rm -rf "${PY_STAGE_DIR}"/lib/python*/turtledemo
rm -f  "${PY_STAGE_DIR}/bin/2to3"* \
        "${PY_STAGE_DIR}/bin/idle"* \
        "${PY_STAGE_DIR}/bin/pydoc"* \
        "${PY_STAGE_DIR}/bin/wheel"* \
        "${PY_STAGE_DIR}/bin/pip"*

# ─── 5. Python venv against the bundled interpreter ──────────────────────────
echo "==> Provisioning Python venv with uv"
VENV_DIR="${STAGE_DIR}/usr/lib/vayobd/venv"

uv venv --python "${UV_PY_BIN}" --relocatable "${VENV_DIR}"
# Install the backend (and its runtime deps) into the venv. `uv pip install`
# does not require pip to be installed inside the venv itself.
uv pip install --quiet --python "${VENV_DIR}/bin/python" "${REPO_ROOT}/backend"

# Re-target the venv's Python at the bundled interpreter. At install time the
# venv will live at /usr/lib/vayobd/venv with python3.X -> ../python/bin/python3.X.
RUNTIME_PY="/usr/lib/vayobd/python/bin/python${TARGET_PY_VERSION}"
rm -f "${VENV_DIR}/bin/python" \
      "${VENV_DIR}/bin/python3" \
      "${VENV_DIR}/bin/python${TARGET_PY_VERSION}"
ln -s "${RUNTIME_PY}" "${VENV_DIR}/bin/python${TARGET_PY_VERSION}"
ln -s "python${TARGET_PY_VERSION}" "${VENV_DIR}/bin/python3"
ln -s python3 "${VENV_DIR}/bin/python"
# Rewrite pyvenv.cfg so `home = ...` points at the bundled python's bin/.
if [[ -f "${VENV_DIR}/pyvenv.cfg" ]]; then
    sed -i "s#^home = .*#home = /usr/lib/vayobd/python/bin#" "${VENV_DIR}/pyvenv.cfg"
fi

# ─── 5. Package ──────────────────────────────────────────────────────────────
echo "==> Running nfpm"
export VAYOBD_VERSION
nfpm package --packager deb -f "${PKG_DIR}/nfpm.yaml" --target "${OUT_DIR}/"

DEB_FILE="$(ls -1t "${OUT_DIR}"/vayobd_*amd64.deb 2>/dev/null | head -1 || true)"
if [[ -z "${DEB_FILE}" ]]; then
    echo "ERROR: nfpm did not produce a .deb in ${OUT_DIR}/" >&2
    exit 1
fi

echo ""
echo "✓ Built: ${DEB_FILE}"
echo "  Version: ${VAYOBD_VERSION}"
echo "  Commit:  ${VAYOBD_COMMIT}"
echo ""
echo "Install with:  sudo apt install ${DEB_FILE}"
echo "Smoke test:    ./scripts/package-smoke-test.sh ${DEB_FILE}"
